#!/bin/bash
# chkconfig: 345 20 80
# description: starts the jetty server

# Source function library.
. /etc/init.d/functions


SERVICE=/usr/local/node_exporter/node_exporter
PROCESS_NAME=/usr/local/node_exporter/node_exporter
SERVICE_NAME=node_exporter
USERNAME=node_exporter


# -------- Core functions --------

# Start the process
function start_service {
  echo "Starting $SERVICE_NAME ..."
  sudo -u $USERNAME bash -c "$SERVICE"
  if [ $? -eq 0 ]
    then
    echo "Successfully started $SERVICE_NAME"
    return 0
  else
    echo "Failed to start $SERVICE_NAME !"
    return 1
  fi
}

# Stop the process
function stop_service {
  echo "Stopping $SERVICE_NAME ..."
  sudo -u $USERNAME bash -c "pkill $SERVICE_NAME"
  if [ $? -eq 0 ]
    then
    echo "Successfully stopped $SERVICE_NAME"
    return 0
  else
    echo "Failed to stop $SERVICE_NAME !"
    return 1
  fi
}

# Check status
function check_status {
  # Check for PID_FILE
  PCOUNT=`sudo -u $USERNAME bash -c "ps -ef | grep $SERVICE_NAME | grep -v grep | wc -l"`

  if [ $PCOUNT -gt 0 ]
    then
    echo "$SERVICE_NAME is running"
    return 0
  else
    echo "$SERVICE_NAME is NOT running"
    return 1 
  fi
}

# -------------------------------------

case "$1" in
  start)
    check_status
    if [ $? -eq 1 ]
      then
      start_service
    fi
    ;;

  stop)
    check_status
    if [ $? -eq 0 ]
      then
      stop_service
    fi
    ;;

  restart)
    check_status
    if [ $? -eq 0 ]
      then
      stop_service
    fi
    start_service
    ;;

  status)
    check_status
    ;;

  *)
    echo "Usage: service $SERVICE_NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
